### ISSUE TITLE
Crashed during search

### ISSUE THREAD

**Issue by KapJI** [noborus/ov#641]
Not exactly sure what triggered this but here is the stacktrace:
```console
$ bat configs.txt
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6343cb]

goroutine 113 [running]:
github.com/noborus/ov/oviewer.(*Root).searchXPos(0xc00032f408, 0xc000651eb8?)
        /home/runner/work/ov/ov/oviewer/search.go:221 +0x6b
github.com/noborus/ov/oviewer.(*Root).searchGo(0xc00032f408, {0x91e698, 0xc000134050}, 0x5f)
        /home/runner/work/ov/ov/oviewer/action.go:188 +0x48
github.com/noborus/ov/oviewer.(*Root).event(0xc000396620?, {0x91e698?, 0xc000134050?}, {0x91bcc0?, 0xc00103a280?})
        /home/runner/work/ov/ov/oviewer/event.go:72 +0x9e
github.com/noborus/ov/oviewer.(*Root).eventLoop(0xc00032f408, {0x91e698, 0xc000134050}, 0xc000614000)
        /home/runner/work/ov/ov/oviewer/event.go:27 +0x115
github.com/noborus/ov/oviewer.(*Root).Run.func1()
        /home/runner/work/ov/ov/oviewer/oviewer.go:649 +0x55
created by github.com/noborus/ov/oviewer.(*Root).Run in goroutine 1
        /home/runner/work/ov/ov/oviewer/oviewer.go:644 +0x388
        
$ ov --version
ov version 0.36.0 rev:d671c94
```

Platform: Linux

**Comment by noborus** [comment]
Thank you for Issue.
This is a bug.

**Comment by KapJI** [comment]
Fixed by #642
